sudo: false

language: java

jdk: oraclejdk7

cache:
  directories:
    - '$HOME/.m2/repository'

env: DISPLAY=:99.0

install: true

#before_install:
# - sudo apt-get update
# - sudo apt-get install gnome-themes-standard
# - sudo apt-get install metacity
# - sudo apt-get install libwebkit-dev

before_script:
 - sh -e /etc/init.d/xvfb start
 - sleep 10 # give xvfb some time to start
 - metacity --sm-disable --replace &
 - sleep 10 # give metacity some time to start
 
script:
 - export
 - mvn -f releng/it.xsemantics.parent/pom.xml clean verify -Dfindbugs.skip=true -Dswtbot.tests.skip=true