#
# Copyright (c) 2013-2017 Lorenzo Bettini.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Lorenzo Bettini - Initial contribution and API
#

language: java

matrix:
  fast_finish: true
  include:
    # always build this environment
    - os: linux
      dist: xenial
      jdk: openjdk8
      services:
      - xvfb
      addons:
        apt:
          packages:
          - metacity
    # only on PR
    - os: osx
      osx_image: xcode10.1
      jdk: openjdk11
      if: type IN (pull_request)

cache:
  directories:
  - $HOME/.m2

install: true

before_install:
# - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
 - echo $JAVA_HOME

before_script:
 - bash -e ./before_script.sh

# Build on MacOSX is triggered only for pull requests
script:
 - export
 - bash -e ./travis_build.sh
